export type GetFieldType =
  | 'fake'
  | 'object'
  | 'token'
  | 'token_member'
  | 'user-entity'
  | 'user-destroy-with-relationship-entity'
  | 'user-admin-entity'
  | 'user-http-entity'
  | 'user-history-entity'
  | 'user-history-destroy-entity'
  | 'history-entity'
  | 'history-http-entity'
  | 'order-entity'
  | 'order-http-entity';
