export type GetFieldType =
  | 'token'
  | 'object'
  | 'fake'
  | 'user-entity'
  | 'user-service-entity'
  | 'user-http-entity'
  | 'basic-entity'
  | 'basic-http-entity'
  | 'basic-destroy-entity'
  | 'price-entity'
  | 'stock-entity'
  | 'variant-entity'
  | 'history-entity'
  | 'product-http-entity'
  | 'file-entity'
  | 'connect-entity';
